[workspace]
members = ["contracts/*", "packages/*"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"
homepage = "https://junonetwork.io"
repository = "https://github.com/CosmosContracts/token-bindings"
version = "0.11.0"

[workspace.dependencies]
cosmwasm-schema = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "zk-mvp" }
cosmwasm-std = { git = "https://github.com/permissionlessweb/cosmwasm", branch = "zk-mvp" }
cw-multi-test = { package = "abstract-cw-multi-test", git = "https://github.com/permissionlessweb/cw-multi-test-fork", branch = "zk-mvp" }
cw-storage-plus = { git = "https://github.com/permissionlessweb/cw-storage-plus", branch = "zk-mvp" }
cw2 = { git = "https://github.com/permissionlessweb/cw-minus", branch = "zk-mvp" }
itertools = "0.14.0"
serde = "1.0"
thiserror = "1.0"

token-bindings = { git = "https://github.com/permissionlessweb/token-bindings", branch = "main" }
token-bindings-test = { path = "./packages/bindings-test", version = "0.11.0" }

[profile.release]
codegen-units = 1
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
panic = 'abort'
incremental = false
# Please do not disable these. Doing so will cause overflow checks in
# all workspace members to stop working. Overflows should be errors.
overflow-checks = true
